module.exports = {
  AEL: {
    HOK: 'Hong Kong',
    KOW: 'Kowloon',
    TSY: 'Tsing Yi',
    AIR: 'Airport',
    AWE: 'AsiaWorld Expo',
  },
  TCL: {
    HOK: 'Hong Kong',
    KOW: 'Kowloon',
    OLY: 'Olympic',
    NAC: 'Nam Cheong',
    LAK: 'Lai King',
    TSY: 'Tsing Yi',
    SUN: 'Sunny Bay',
    TUC: 'Tung Chung',
  },
  WRL: {
    HUH: 'Hung Hom',
    ETS: 'East Tsim Sha Tsui',
    AUS: 'Austin',
    NAC: 'Nam Cheong',
    MEF: 'Mei Foo',
    TWW: 'Tsuen Wan West',
    KSR: 'Kam Sheung Road',
    YUL: 'Yuen Long',
    LOP: 'Long Ping',
    TIS: 'Tin Shui Wai',
    SIH: 'Siu Hong',
    TUM: 'Tuen Mun',
  },
  TKL: {
    NOP: 'North Point',
    QUB: 'Quarry Bay',
    YAT: 'Yau Tong',
    TIK: 'Tiu Keng Leng',
    TKO: 'Tseung Kwan O',
    LHP: 'LOHAS Park',
    HAH: 'Hang Hau',
    POA: 'Po Lam',
  },
  TML: {
    WKS: 'Wu Kai Sha',
    MOS: 'Ma On Shan',
    HEO: 'Heng On',
    TSH: 'Tai Shui Hang',
    SHM: 'Shek Mun',
    CIO: 'City One',
    STW: 'Sha Tin Wai',
    CKT: 'Che Kung Temple',
    TAW: 'Tai Wai',
    HIK: 'Hin Keng',
    DIH: 'Diamond Hill',
    KAT: 'Kai Tak',
    SUW: 'Sung Wong Toi',
    TKW: 'To Kwa Wan',
    HOM: 'Ho Man Tin',
    HUH: 'Hung Hom',
    ETS: 'East Tsim Sha Tsui',
    AUS: 'Austin',
    NAC: 'Nam Cheong',
    MEF: 'Mei Foo',
    TWW: 'Tsuen Wan West',
    KSR: 'Kam Sheung Road',
    YUL: 'Yuen Long',
    LOP: 'Long Ping',
    TIS: 'Tin Shui Wai',
    SIH: 'Siu Hong',
    TUM: 'Tuen Mun',
  },
  TKL: {
    NOP: 'North Point',
    QUB: 'Quarry Bay',
    YAT: 'Yau Tong',
    TIK: 'Tiu Keng Leng',
    TKO: 'Tseung Kwan O',
    LHP: 'LOHAS Park',
    HAH: 'Hang Hau',
    POA: 'Po Lam',
  },
  EAL: {
    ADM: 'Admiralty',
    EXC: 'Exhibition Centre',
    HUH: 'Hung Hom',
    MKK: 'Mong Kok East',
    KOT: 'Kowloon Tong',
    TAW: 'Tai Wai',
    SHT: 'Sha Tin',
    FOT: 'Fo Tan',
    RAC: 'Racecourse',
    UNI: 'University',
    TAP: 'Tai Po Market',
    TWO: 'Tai Wo',
    FAN: 'Fanling',
    SHS: 'Sheung Shui',
    LOW: 'Lo Wu',
    LMC: 'Lok Ma Chau',
  },
  SIL: {
    ADM: 'Admiralty',
    OCP: 'Ocean Park',
    WCH: 'Wong Chuk Hang',
    LET: 'Lei Tung',
    SOH: 'South Horizons',
  },
  TWL: {
    CEN: 'Central',
    ADM: 'Admiralty',
    TST: 'Tsim Sha Tsui',
    JOR: 'Jordan',
    YMT: 'Yau Ma Tei',
    MOK: 'Mong Kok',
    PRE: 'Price Edward',
    SSP: 'Sham Shui Po',
    CSW: 'Cheung Sha Wan',
    LCK: 'Lai Chi Kok',
    MEF: 'Mei Foo',
    LAK: 'Lai King',
    KWF: 'Kwai Fong',
    KWH: 'Kwai Hing',
    TWH: 'Tai Wo Hau',
    TSW: 'Tsuen Wan',
  },
  ISL: {
    KET: 'Kennedy Town',
    HKU: 'HKU',
    SYP: 'Sai Ying Pun',
    SHW: 'Sheung Wan',
    CEN: 'Central',
    ADM: 'Admiralty',
    WAC: 'Wan Chai',
    CAB: 'Causeway Bay',
    TIH: 'Tin Hau',
    FOH: 'Fortress Hill',
    NOP: 'North Point',
    QUB: 'Quarry Bay',
    TAK: 'Tai Koo',
    SWH: 'Sai Wan Ho',
    SKW: 'Shau Kei Wan',
    HFC: 'Heng Fa Chuen',
    CHW: 'Chai Wa',
  },
  KTL: {
    WHA: 'Whampoa',
    HOM: 'Ho Man Tin',
    YMT: 'Yau Ma Tei',
    MOK: 'Mong Kok',
    PRE: 'Prince Edward',
    SKM: 'Shek Kip Mei',
    KOT: 'Kowloon Tong',
    LOF: 'Lok Fu',
    WTS: 'Wong Tai Sin',
    DIH: 'Diamond Hill',
    CHH: 'Choi Hung',
    KOB: 'Kowloon Bay',
    NTK: 'Ngau Tau Kok',
    KWT: 'Kwun Tong',
    LAT: 'Lam Tin',
    YAT: 'Yau Tong',
    TIK: 'Tiu Keng Leng',
  },
};
