module.exports = {
  AEL: {
    HOK: 'Hong Kong',
    KOW: 'Kowloon',
    TSY: 'Tsing Yi',
    AIR: 'Airport',
    AWE: 'AsiaWorld Expo',
  },
  TCL: {
    HOK: 'Hong Kong',
    KOW: 'Kowloon',
    OLY: 'Olympic',
    NAC: 'Nam Cheong',
    LAK: 'Lai King',
    TSY: 'Tsing Yi',
    SUN: 'Sunny Bay',
    TUC: 'Tung Chung',
  },
  WRL: {
    HUH: 'Hung Hom',
    ETS: 'East Tsim Sha Tsui',
    AUS: 'Austin',
    NAC: 'Nam Cheong',
    MEF: 'Mei Foo',
    TWW: 'Tsuen Wan West',
    KSR: 'Kam Sheung Road',
    YUL: 'Yuen Long',
    LOP: 'Long Ping',
    TIS: 'Tin Shui Wai',
    SIH: 'Siu Hong',
    TUM: 'Tuen Mun',
  },
  TKL: {
    NOP: 'North Point',
    QUB: 'Quarry Bay',
    YAT: 'Yau Tong',
    TIK: 'Tiu Keng Leng',
    TKO: 'Tseung Kwan O',
    LHP: 'LOHAS Park',
    HAH: 'Hang Hau',
    POA: 'Po Lam',
  },
};
